### ISSUE TITLE
Problem with the camera installed first

### ISSUE THREAD

**Issue by fjms** [darryncampbell/darryncampbell-cordova-plugin-intent#11] opened 2017-07-03 09:24 UTC
I installed the plugin of the camera first, but the camera does not work with the latest version of this plugin.

How should I proceed to force the loading order of the plugins? 

Thank

**Comment by darryncampbell** [comment] 2017-07-03 09:31
Hi, what error do you get?

**Comment by fjms** [comment] 2017-07-03 11:08
Unfortunately, the error is not very descriptive.

length=1; index=1

The code run fine without your plugin.

`const options: CameraOptions = {
        quality: 75,
        destinationType: this.camera.DestinationType.FILE_URI,
        sourceType: this.camera.PictureSourceType.CAMERA,
        encodingType: this.camera.EncodingType.JPEG,
        mediaType: this.camera.MediaType.PICTURE,
        correctOrientation: true,
        saveToPhotoAlbum: false
      }
      this.camera.getPicture(options).then((fileUri) => {
        let n = this.file.externalCacheDirectory.indexOf("cache");
        let name = fileUri.slice(n + 6);
        let fileEntry = {};
        fileEntry['name'] = name;
        fileEntry['path'] = this.file.externalCacheDirectory;
        fileEntry['nativeURL'] = fileUri;
        this.listServicesImages.unshift(fileEntry);
        resolve(fileUri);
      }, (err) => {
        console.log('Camera getPicture error 0');
        console.log(err);
        reject(err);
      })`

More info:
`global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 1.3.12
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.4.2

System:

    Node       : v6.11.0
    OS         : Windows 7
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10`

Plugins
`> cordova plugin ls
✔ Running command - done!
com-darryncampbell-cordova-plugin-intent 0.0.13 "Intent Shim"
cordova-fabric-plugin 1.1.9 "cordova-fabric-plugin"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-geolocation 2.4.3 "Geolocation"
cordova-plugin-globalization 1.0.7 "Globalization"
cordova-plugin-inappbrowser 1.7.1 "InAppBrowser"
cordova-plugin-network-information 1.3.3 "Network Information"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.1 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-toast 2.6.0 "Toast"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-sqlite-storage 2.0.4 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 3.6.5 "Diagnostic"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-nfc 0.6.6 "NFC"`

**Comment by darryncampbell** [comment] 2017-07-03 11:33
:/ No, not very helpful like you say.  Try using version 0.0.7 of the plugin as that should have no interaction with the Camera plugin so you should not see any issues with that version.  

For the latest version of this plugin, if you need to use that the first thing to check is that you have a provider_paths.xml file located at <your app>\platforms\android\res\xml\.  That file is shared with the Camera plugin so possibly something is strange there.  If the file is present, if it has anything other than a single entry for external-path with path '.' then it is possible I have misunderstood the complexity of the Camera.

**Comment by darryncampbell** [comment] 2017-07-03 12:02
I just committed https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/commit/8245d594cbe45096df89fe85c697121847e56162, can you please test against the master branch of this plugin?  I believe the root cause was a mismatch between the names of the external-path file.  You might have to delete the provider_paths.xml file I mentioned in the previous comment and uninstall / reinstall both plugins.

**Comment by fjms** [comment] 2017-07-03 12:03
Ok. I'll try

**Comment by fjms** [comment] 2017-07-03 12:43
It works perfectly. Thank you.

**Comment by darryncampbell** [comment] 2017-07-03 12:46
👍

**Closed by darryncampbell** 2017-07-03 12:46 UTC
